version: '3.4'
services:
  pict_api:
    build:
      context: ./backend
      target: target_for_development
    environment:
      NODE_ENV: development
    container_name: pict_api
    volumes:
      - ./backend:/root/api/
    working_dir: /root/api/
    command: air
    ports:
      - '8080:8080'
